/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador_FRM_Juego;

/**
 *
 * @author darkm
 */
public class JP_AgregarRank extends javax.swing.JPanel {

    /**
     * Creates new form JP_AgregarRank
     */
    Controlador_FRM_Juego controlador_FRM_Juego;
    public JP_AgregarRank() {
        initComponents();
        setSize(1000,700);
    }
    public void agregarControlador(Controlador_FRM_Juego controlador_FRM_Juego)
    {
        this.controlador_FRM_Juego=controlador_FRM_Juego;
        btn_Registrar.addActionListener(controlador_FRM_Juego);
    }
    public void llenarInformacion(String puntos,String fecha)
    {
        jt_Puntos.setText(""+puntos);
        jt_Fecha.setText(""+fecha);
    }
    public String devolverPuntos()
    {
        return jt_Puntos.getText();
    }
    public String devolverFecha()
    {
        return jt_Fecha.getText();
    }
    public String devolverNombre()
    {
        return jt_Nombre.getText();
    }
    public void vaciarTexto()
    {
        jt_Nombre.setText("");
        jt_Puntos.setText("");
        jt_Fecha.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jt_Nombre = new javax.swing.JTextField();
        jt_Puntos = new javax.swing.JTextField();
        jt_Fecha = new javax.swing.JTextField();
        btn_Registrar = new javax.swing.JButton();
        jl_Layout = new javax.swing.JLabel();
        jl_Fondo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jt_Nombre.setBackground(new java.awt.Color(51, 51, 51));
        jt_Nombre.setFont(new java.awt.Font("Meiryo", 0, 24)); // NOI18N
        jt_Nombre.setForeground(new java.awt.Color(255, 255, 255));
        jt_Nombre.setOpaque(false);
        add(jt_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 370, 40));

        jt_Puntos.setBackground(new java.awt.Color(51, 51, 51));
        jt_Puntos.setFont(new java.awt.Font("Meiryo", 0, 24)); // NOI18N
        jt_Puntos.setForeground(new java.awt.Color(255, 255, 255));
        jt_Puntos.setFocusable(false);
        jt_Puntos.setOpaque(false);
        add(jt_Puntos, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, 370, 40));

        jt_Fecha.setBackground(new java.awt.Color(51, 51, 51));
        jt_Fecha.setFont(new java.awt.Font("Meiryo", 0, 24)); // NOI18N
        jt_Fecha.setForeground(new java.awt.Color(255, 255, 255));
        jt_Fecha.setFocusable(false);
        jt_Fecha.setOpaque(false);
        add(jt_Fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 420, 370, 40));

        btn_Registrar.setBackground(new java.awt.Color(5, 5, 24));
        btn_Registrar.setFont(new java.awt.Font("Hemi Head Rg", 0, 24)); // NOI18N
        btn_Registrar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Registrar.setText("Registrar");
        btn_Registrar.setBorderPainted(false);
        add(btn_Registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 620, 160, 50));

        jl_Layout.setFont(new java.awt.Font("Hemi Head Rg", 1, 48)); // NOI18N
        jl_Layout.setForeground(new java.awt.Color(255, 255, 255));
        jl_Layout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/IngresarNombre-11.png"))); // NOI18N
        add(jl_Layout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jl_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/Fondo_Juego.png"))); // NOI18N
        add(jl_Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2500, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Registrar;
    private javax.swing.JLabel jl_Fondo;
    private javax.swing.JLabel jl_Layout;
    private javax.swing.JTextField jt_Fecha;
    private javax.swing.JTextField jt_Nombre;
    private javax.swing.JTextField jt_Puntos;
    // End of variables declaration//GEN-END:variables
}
