/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador_FRM_Juego;
import javax.swing.Icon;

/**
 *
 * @author darkm
 */
public class JP_Controles extends javax.swing.JPanel {

    /**
     * Creates new form JP_Controles
     */
    Icon menu1,menu2,menu3,hist1,hist2,hist3;
    Controlador_FRM_Juego controlador_FRM_Juego;
    public JP_Controles() {
        initComponents();
        menu1=new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/BotonMenu1.png"));
        menu2=new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/BotonMenu2.png"));
        hist1=new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/BotonControles1.png"));
        hist2=new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/BotonControles2.png"));
    }
    public void layoutControl(boolean habilitado)
    {
        jl_ControlHistoria.setVisible(habilitado);
        jl_ControlMenu.setVisible(habilitado);
    }
    public void agregarControlador(Controlador_FRM_Juego controlador_FRM_Juego)
    {
        this.controlador_FRM_Juego=controlador_FRM_Juego;
        btn_Menu.addActionListener(controlador_FRM_Juego);
        btn_Historia.addActionListener(controlador_FRM_Juego);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_ControlHistoria = new javax.swing.JLabel();
        jl_ControlMenu = new javax.swing.JLabel();
        btn_Menu = new javax.swing.JButton();
        btn_Historia = new javax.swing.JButton();
        jl_Controles = new javax.swing.JLabel();
        jl_Fondo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_ControlHistoria.setFont(new java.awt.Font("Hemi Head Rg", 1, 18)); // NOI18N
        jl_ControlHistoria.setForeground(new java.awt.Color(255, 255, 255));
        jl_ControlHistoria.setText("2");
        add(jl_ControlHistoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 590, 20, -1));

        jl_ControlMenu.setFont(new java.awt.Font("Hemi Head Rg", 1, 18)); // NOI18N
        jl_ControlMenu.setForeground(new java.awt.Color(255, 255, 255));
        jl_ControlMenu.setText("1");
        add(jl_ControlMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 590, 20, -1));

        btn_Menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/BotonMenu2.png"))); // NOI18N
        btn_Menu.setActionCommand("MenuC");
        btn_Menu.setContentAreaFilled(false);
        btn_Menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_MenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_MenuMouseExited(evt);
            }
        });
        add(btn_Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 610, -1, -1));

        btn_Historia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/BotonControles2.png"))); // NOI18N
        btn_Historia.setActionCommand("HistoriaC");
        btn_Historia.setBorderPainted(false);
        btn_Historia.setContentAreaFilled(false);
        btn_Historia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_HistoriaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_HistoriaMouseExited(evt);
            }
        });
        add(btn_Historia, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 610, -1, -1));

        jl_Controles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/Controles.png"))); // NOI18N
        add(jl_Controles, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, -1, -1));

        jl_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/Fondo_Juego.png"))); // NOI18N
        add(jl_Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4000, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_MenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_MenuMouseEntered
        btn_Menu.setIcon(menu1);
    }//GEN-LAST:event_btn_MenuMouseEntered

    private void btn_MenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_MenuMouseExited
        btn_Menu.setIcon(menu2);
    }//GEN-LAST:event_btn_MenuMouseExited

    private void btn_HistoriaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_HistoriaMouseExited
        btn_Historia.setIcon(hist2);
    }//GEN-LAST:event_btn_HistoriaMouseExited

    private void btn_HistoriaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_HistoriaMouseEntered
        btn_Historia.setIcon(hist1);
    }//GEN-LAST:event_btn_HistoriaMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Historia;
    private javax.swing.JButton btn_Menu;
    private javax.swing.JLabel jl_ControlHistoria;
    private javax.swing.JLabel jl_ControlMenu;
    private javax.swing.JLabel jl_Controles;
    private javax.swing.JLabel jl_Fondo;
    // End of variables declaration//GEN-END:variables
}
