/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador_FRM_Juego;
import javax.swing.Icon;

/**
 *
 * @author darkm
 */
public class JP_Derrota extends javax.swing.JPanel {

    /**
     * Creates new form JP_Derrota
     */
    Controlador_FRM_Juego controlador_FRM_Juego;
    Icon home1,home2,home3,rein1,rein2,rein3;
    public JP_Derrota() {
        initComponents();
        home1=new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/Home1.png"));
        home2=new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/Home2.png"));
        home3=new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/Home3.png"));
        rein1=new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/Reiniciar1.png"));
        rein2=new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/Reiniciar2.png"));
        rein3=new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/Reiniciar3.png"));
    }
    public void agregarControlador(Controlador_FRM_Juego controlador_FRM_Juego)
    {
        this.controlador_FRM_Juego=controlador_FRM_Juego;
        btn_Menu.addActionListener(controlador_FRM_Juego);
        btn_Reiniciar.addActionListener(controlador_FRM_Juego);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_Perdiste = new javax.swing.JLabel();
        btn_Menu = new javax.swing.JButton();
        btn_Reiniciar = new javax.swing.JButton();
        jl_Fondo = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_Perdiste.setFont(new java.awt.Font("Source Sans Pro", 0, 48)); // NOI18N
        jl_Perdiste.setForeground(new java.awt.Color(255, 204, 204));
        jl_Perdiste.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/FIN_DEL_JUEGO.png"))); // NOI18N
        add(jl_Perdiste, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));

        btn_Menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/Home2.png"))); // NOI18N
        btn_Menu.setActionCommand("Menu");
        btn_Menu.setBorderPainted(false);
        btn_Menu.setContentAreaFilled(false);
        btn_Menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_MenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_MenuMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_MenuMousePressed(evt);
            }
        });
        add(btn_Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, -1, -1));

        btn_Reiniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/Reiniciar2.png"))); // NOI18N
        btn_Reiniciar.setActionCommand("reiniciar");
        btn_Reiniciar.setBorderPainted(false);
        btn_Reiniciar.setContentAreaFilled(false);
        btn_Reiniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_ReiniciarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_ReiniciarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_ReiniciarMousePressed(evt);
            }
        });
        add(btn_Reiniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 350, -1, -1));

        jl_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/Semi-Oscuro.png"))); // NOI18N
        add(jl_Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_MenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_MenuMouseExited
        btn_Menu.setIcon(home2);
    }//GEN-LAST:event_btn_MenuMouseExited

    private void btn_MenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_MenuMouseEntered
        btn_Menu.setIcon(home1);
    }//GEN-LAST:event_btn_MenuMouseEntered

    private void btn_MenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_MenuMousePressed
        btn_Menu.setIcon(home3);
    }//GEN-LAST:event_btn_MenuMousePressed

    private void btn_ReiniciarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ReiniciarMouseExited
        btn_Reiniciar.setIcon(rein2);
    }//GEN-LAST:event_btn_ReiniciarMouseExited

    private void btn_ReiniciarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ReiniciarMouseEntered
        btn_Reiniciar.setIcon(rein1);
    }//GEN-LAST:event_btn_ReiniciarMouseEntered

    private void btn_ReiniciarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ReiniciarMousePressed
        btn_Reiniciar.setIcon(rein3);
    }//GEN-LAST:event_btn_ReiniciarMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Menu;
    private javax.swing.JButton btn_Reiniciar;
    private javax.swing.JLabel jl_Fondo;
    private javax.swing.JLabel jl_Perdiste;
    // End of variables declaration//GEN-END:variables
}
