/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador_FRM_Juego;
import javax.swing.Icon;

/**
 *
 * @author darkm
 */
public class JP_Historia extends javax.swing.JPanel {

    /**
     * Creates new form JP_Historia
     */
    Icon menu1,menu2,cont1,cont2;
    Controlador_FRM_Juego controlador_FRM_Juego;
    public JP_Historia() {
        initComponents();
        menu1=new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/BotonMenu1.png"));
        menu2=new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/BotonMenu2.png"));
        cont1=new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/BotonHistoria1.png"));
        cont2=new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/BotonHistoria2.png"));
    }
    public void layoutControl(boolean habilitado)
    {
        jl_ControlControles.setVisible(habilitado);
        jl_ControlMenu.setVisible(habilitado);
    }
    public void agregarControlador(Controlador_FRM_Juego controlador_FRM_Juego)
    {
        this.controlador_FRM_Juego=controlador_FRM_Juego;
        btn_Menu.addActionListener(controlador_FRM_Juego);
        btn_Controles.addActionListener(controlador_FRM_Juego);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_ControlMenu = new javax.swing.JLabel();
        jl_ControlControles = new javax.swing.JLabel();
        btn_Menu = new javax.swing.JButton();
        btn_Controles = new javax.swing.JButton();
        jl_Historia = new javax.swing.JLabel();
        jl_Fondo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_ControlMenu.setFont(new java.awt.Font("Hemi Head Rg", 1, 18)); // NOI18N
        jl_ControlMenu.setForeground(new java.awt.Color(255, 255, 255));
        jl_ControlMenu.setText("1");
        add(jl_ControlMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 590, -1, -1));

        jl_ControlControles.setFont(new java.awt.Font("Hemi Head Rg", 1, 18)); // NOI18N
        jl_ControlControles.setForeground(new java.awt.Color(255, 255, 255));
        jl_ControlControles.setText("3");
        add(jl_ControlControles, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 590, -1, -1));

        btn_Menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/BotonMenu2.png"))); // NOI18N
        btn_Menu.setActionCommand("MenuH");
        btn_Menu.setBorderPainted(false);
        btn_Menu.setContentAreaFilled(false);
        btn_Menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_MenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_MenuMouseExited(evt);
            }
        });
        add(btn_Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 610, -1, -1));

        btn_Controles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/BotonHistoria2.png"))); // NOI18N
        btn_Controles.setActionCommand("ControlesH");
        btn_Controles.setBorderPainted(false);
        btn_Controles.setContentAreaFilled(false);
        btn_Controles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_ControlesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_ControlesMouseExited(evt);
            }
        });
        add(btn_Controles, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 610, -1, -1));

        jl_Historia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/Historia.png"))); // NOI18N
        add(jl_Historia, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jl_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/Fondo_Juego.png"))); // NOI18N
        add(jl_Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5000, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_MenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_MenuMouseExited
        btn_Menu.setIcon(menu2);
    }//GEN-LAST:event_btn_MenuMouseExited

    private void btn_MenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_MenuMouseEntered
        btn_Menu.setIcon(menu1);
    }//GEN-LAST:event_btn_MenuMouseEntered

    private void btn_ControlesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ControlesMouseExited
        btn_Controles.setIcon(cont2);
    }//GEN-LAST:event_btn_ControlesMouseExited

    private void btn_ControlesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ControlesMouseEntered
        btn_Controles.setIcon(cont1);
    }//GEN-LAST:event_btn_ControlesMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Controles;
    private javax.swing.JButton btn_Menu;
    private javax.swing.JLabel jl_ControlControles;
    private javax.swing.JLabel jl_ControlMenu;
    private javax.swing.JLabel jl_Fondo;
    private javax.swing.JLabel jl_Historia;
    // End of variables declaration//GEN-END:variables
}
