/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador_FRM_Juego;
import javax.swing.Icon;

/**
 *
 * @author darkm
 */
public class JP_Rank extends javax.swing.JPanel {

    /**
     * Creates new form JP_Rank
     */
    Controlador_FRM_Juego controlador_FRM_Juego;
    Icon menu1,menu2;
    public JP_Rank() {
        initComponents();
        menu1=new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/BotonMenu1.png"));
        menu2=new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/BotonMenu2.png"));
    }
    public void layoutControl(boolean habilitado)
    {
        jl_ControlMenu.setVisible(habilitado);
    }
    public void agregarControlador(Controlador_FRM_Juego controlador_FRM_Juego)
    {
        this.controlador_FRM_Juego=controlador_FRM_Juego;
        btn_Menu.addActionListener(controlador_FRM_Juego);
    }
    public void llenarRank(String[][] puntuaciones)
    {
        //- - Nombres
        jl_1.setText(puntuaciones[0][0]);
        jl_2.setText(puntuaciones[1][0]);
        jl_3.setText(puntuaciones[2][0]);
        jl_4.setText(puntuaciones[3][0]);
        jl_5.setText(puntuaciones[4][0]);
        jl_6.setText(puntuaciones[5][0]);
        jl_7.setText(puntuaciones[6][0]);
        jl_8.setText(puntuaciones[7][0]);
        jl_9.setText(puntuaciones[8][0]);
        jl_10.setText(puntuaciones[9][0]);
        
        //- - Puntos
        jl_11.setText(puntuaciones[0][1]);
        jl_12.setText(puntuaciones[1][1]);
        jl_13.setText(puntuaciones[2][1]);
        jl_14.setText(puntuaciones[3][1]);
        jl_15.setText(puntuaciones[4][1]);
        jl_16.setText(puntuaciones[5][1]);
        jl_17.setText(puntuaciones[6][1]);
        jl_18.setText(puntuaciones[7][1]);
        jl_19.setText(puntuaciones[8][1]);
        jl_20.setText(puntuaciones[9][1]);
        
        //- - Fechas
        jl_21.setText(puntuaciones[0][2]);
        jl_22.setText(puntuaciones[1][2]);
        jl_23.setText(puntuaciones[2][2]);
        jl_24.setText(puntuaciones[3][2]);
        jl_25.setText(puntuaciones[4][2]);
        jl_26.setText(puntuaciones[5][2]);
        jl_27.setText(puntuaciones[6][2]);
        jl_28.setText(puntuaciones[7][2]);
        jl_29.setText(puntuaciones[8][2]);
        jl_30.setText(puntuaciones[9][2]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_ControlMenu = new javax.swing.JLabel();
        btn_Menu = new javax.swing.JButton();
        jl_1 = new javax.swing.JLabel();
        jl_2 = new javax.swing.JLabel();
        jl_3 = new javax.swing.JLabel();
        jl_4 = new javax.swing.JLabel();
        jl_5 = new javax.swing.JLabel();
        jl_6 = new javax.swing.JLabel();
        jl_7 = new javax.swing.JLabel();
        jl_8 = new javax.swing.JLabel();
        jl_9 = new javax.swing.JLabel();
        jl_10 = new javax.swing.JLabel();
        jl_11 = new javax.swing.JLabel();
        jl_12 = new javax.swing.JLabel();
        jl_13 = new javax.swing.JLabel();
        jl_14 = new javax.swing.JLabel();
        jl_15 = new javax.swing.JLabel();
        jl_16 = new javax.swing.JLabel();
        jl_17 = new javax.swing.JLabel();
        jl_18 = new javax.swing.JLabel();
        jl_19 = new javax.swing.JLabel();
        jl_20 = new javax.swing.JLabel();
        jl_21 = new javax.swing.JLabel();
        jl_22 = new javax.swing.JLabel();
        jl_23 = new javax.swing.JLabel();
        jl_24 = new javax.swing.JLabel();
        jl_25 = new javax.swing.JLabel();
        jl_26 = new javax.swing.JLabel();
        jl_27 = new javax.swing.JLabel();
        jl_28 = new javax.swing.JLabel();
        jl_29 = new javax.swing.JLabel();
        jl_30 = new javax.swing.JLabel();
        jl_Layout = new javax.swing.JLabel();
        jl_Fondo = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1000, 700));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_ControlMenu.setFont(new java.awt.Font("Hemi Head Rg", 1, 18)); // NOI18N
        jl_ControlMenu.setForeground(new java.awt.Color(255, 255, 255));
        jl_ControlMenu.setText("1");
        add(jl_ControlMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 590, 20, -1));

        btn_Menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/BotonMenu2.png"))); // NOI18N
        btn_Menu.setActionCommand("MenuR");
        btn_Menu.setBorderPainted(false);
        btn_Menu.setContentAreaFilled(false);
        btn_Menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_MenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_MenuMouseExited(evt);
            }
        });
        add(btn_Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 610, -1, -1));

        jl_1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jl_1.setForeground(new java.awt.Color(255, 255, 255));
        jl_1.setText("1:");
        add(jl_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 215, 170, -1));

        jl_2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jl_2.setForeground(new java.awt.Color(255, 255, 255));
        jl_2.setText("2:");
        add(jl_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 170, -1));

        jl_3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jl_3.setForeground(new java.awt.Color(255, 255, 255));
        jl_3.setText("3:");
        add(jl_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 285, 170, -1));

        jl_4.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jl_4.setForeground(new java.awt.Color(255, 255, 255));
        jl_4.setText("4:");
        add(jl_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 170, -1));

        jl_5.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jl_5.setForeground(new java.awt.Color(255, 255, 255));
        jl_5.setText("5:");
        add(jl_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 355, 170, -1));

        jl_6.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jl_6.setForeground(new java.awt.Color(255, 255, 255));
        jl_6.setText("6:");
        add(jl_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, 170, -1));

        jl_7.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jl_7.setForeground(new java.awt.Color(255, 255, 255));
        jl_7.setText("7:");
        add(jl_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 425, 170, -1));

        jl_8.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jl_8.setForeground(new java.awt.Color(255, 255, 255));
        jl_8.setText("8:");
        add(jl_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 460, 170, -1));

        jl_9.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jl_9.setForeground(new java.awt.Color(255, 255, 255));
        jl_9.setText("9:");
        add(jl_9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 495, 170, -1));

        jl_10.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jl_10.setForeground(new java.awt.Color(255, 255, 255));
        jl_10.setText("10:");
        add(jl_10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 530, 170, -1));

        jl_11.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jl_11.setForeground(new java.awt.Color(255, 255, 255));
        jl_11.setText("Puntos:");
        add(jl_11, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 215, 120, -1));

        jl_12.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jl_12.setForeground(new java.awt.Color(255, 255, 255));
        jl_12.setText("Puntos:");
        add(jl_12, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, 120, -1));

        jl_13.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jl_13.setForeground(new java.awt.Color(255, 255, 255));
        jl_13.setText("Puntos:");
        add(jl_13, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 285, 120, -1));

        jl_14.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jl_14.setForeground(new java.awt.Color(255, 255, 255));
        jl_14.setText("Puntos:");
        add(jl_14, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, 120, -1));

        jl_15.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jl_15.setForeground(new java.awt.Color(255, 255, 255));
        jl_15.setText("Puntos:");
        add(jl_15, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 355, 120, -1));

        jl_16.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jl_16.setForeground(new java.awt.Color(255, 255, 255));
        jl_16.setText("Puntos:");
        add(jl_16, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 390, 120, -1));

        jl_17.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jl_17.setForeground(new java.awt.Color(255, 255, 255));
        jl_17.setText("Puntos:");
        add(jl_17, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 425, 120, -1));

        jl_18.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jl_18.setForeground(new java.awt.Color(255, 255, 255));
        jl_18.setText("Puntos:");
        add(jl_18, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 460, 120, -1));

        jl_19.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jl_19.setForeground(new java.awt.Color(255, 255, 255));
        jl_19.setText("Puntos:");
        add(jl_19, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 495, 120, -1));

        jl_20.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jl_20.setForeground(new java.awt.Color(255, 255, 255));
        jl_20.setText("Puntos:");
        add(jl_20, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 530, 120, -1));

        jl_21.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jl_21.setForeground(new java.awt.Color(255, 255, 255));
        jl_21.setText("Fecha:");
        add(jl_21, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 215, 120, -1));

        jl_22.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jl_22.setForeground(new java.awt.Color(255, 255, 255));
        jl_22.setText("Fecha:");
        add(jl_22, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 250, 120, -1));

        jl_23.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jl_23.setForeground(new java.awt.Color(255, 255, 255));
        jl_23.setText("Fecha:");
        add(jl_23, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 285, 120, -1));

        jl_24.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jl_24.setForeground(new java.awt.Color(255, 255, 255));
        jl_24.setText("Fecha:");
        add(jl_24, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 320, 120, -1));

        jl_25.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jl_25.setForeground(new java.awt.Color(255, 255, 255));
        jl_25.setText("Fecha:");
        add(jl_25, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 355, 120, -1));

        jl_26.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jl_26.setForeground(new java.awt.Color(255, 255, 255));
        jl_26.setText("Fecha:");
        add(jl_26, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 390, 120, -1));

        jl_27.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jl_27.setForeground(new java.awt.Color(255, 255, 255));
        jl_27.setText("Fecha:");
        add(jl_27, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 425, 120, -1));

        jl_28.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jl_28.setForeground(new java.awt.Color(255, 255, 255));
        jl_28.setText("Fecha:");
        add(jl_28, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 460, 120, -1));

        jl_29.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jl_29.setForeground(new java.awt.Color(255, 255, 255));
        jl_29.setText("Fecha:");
        add(jl_29, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 495, 120, -1));

        jl_30.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jl_30.setForeground(new java.awt.Color(255, 255, 255));
        jl_30.setText("Fecha:");
        add(jl_30, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 530, 120, -1));

        jl_Layout.setBackground(new java.awt.Color(255, 255, 255));
        jl_Layout.setFont(new java.awt.Font("Noto Mono", 1, 48)); // NOI18N
        jl_Layout.setForeground(new java.awt.Color(255, 255, 255));
        jl_Layout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_Layout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/Rank-10.png"))); // NOI18N
        add(jl_Layout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jl_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/Fondo_Juego.png"))); // NOI18N
        add(jl_Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6000, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_MenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_MenuMouseEntered
        btn_Menu.setIcon(menu1);
    }//GEN-LAST:event_btn_MenuMouseEntered

    private void btn_MenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_MenuMouseExited
        btn_Menu.setIcon(menu2);
    }//GEN-LAST:event_btn_MenuMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Menu;
    private javax.swing.JLabel jl_1;
    private javax.swing.JLabel jl_10;
    private javax.swing.JLabel jl_11;
    private javax.swing.JLabel jl_12;
    private javax.swing.JLabel jl_13;
    private javax.swing.JLabel jl_14;
    private javax.swing.JLabel jl_15;
    private javax.swing.JLabel jl_16;
    private javax.swing.JLabel jl_17;
    private javax.swing.JLabel jl_18;
    private javax.swing.JLabel jl_19;
    private javax.swing.JLabel jl_2;
    private javax.swing.JLabel jl_20;
    private javax.swing.JLabel jl_21;
    private javax.swing.JLabel jl_22;
    private javax.swing.JLabel jl_23;
    private javax.swing.JLabel jl_24;
    private javax.swing.JLabel jl_25;
    private javax.swing.JLabel jl_26;
    private javax.swing.JLabel jl_27;
    private javax.swing.JLabel jl_28;
    private javax.swing.JLabel jl_29;
    private javax.swing.JLabel jl_3;
    private javax.swing.JLabel jl_30;
    private javax.swing.JLabel jl_4;
    private javax.swing.JLabel jl_5;
    private javax.swing.JLabel jl_6;
    private javax.swing.JLabel jl_7;
    private javax.swing.JLabel jl_8;
    private javax.swing.JLabel jl_9;
    private javax.swing.JLabel jl_ControlMenu;
    private javax.swing.JLabel jl_Fondo;
    private javax.swing.JLabel jl_Layout;
    // End of variables declaration//GEN-END:variables
}
