/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador_FRM_Juego;
import javax.swing.Icon;

/**
 *
 * @author darkm
 */
public class Pausa extends javax.swing.JPanel {

    /**
     * Creates new form Pausa
     */
    Controlador_FRM_Juego controlador_FRM_Juego;
    Icon rean1,rean2,rean3,home1,home2,home3;
    public Pausa() {
        initComponents();
        rean1=new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/Play1.png"));
        rean2=new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/Play2.png"));
        rean3=new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/Play3.png"));
        home1=new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/Home1.png"));
        home2=new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/Home2.png"));
        home3=new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/Home3.png"));
    }
    public void layoutControl(boolean habilitado)
    {
        jl_ControlMenu.setVisible(habilitado);
        jl_ControlReanudar.setVisible(habilitado);
    }
    public void agregarControlador(Controlador_FRM_Juego controlador_FRM_Juego)
    {
        this.controlador_FRM_Juego=controlador_FRM_Juego;
        btn_Reanudar.addActionListener(controlador_FRM_Juego);
        btn_Menu.addActionListener(controlador_FRM_Juego);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_Menu = new javax.swing.JButton();
        btn_Reanudar = new javax.swing.JButton();
        jl_ControlMenu = new javax.swing.JLabel();
        jl_ControlReanudar = new javax.swing.JLabel();
        jl_Fondo = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/Home2.png"))); // NOI18N
        btn_Menu.setActionCommand("Menu");
        btn_Menu.setBorderPainted(false);
        btn_Menu.setContentAreaFilled(false);
        btn_Menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_MenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_MenuMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_MenuMousePressed(evt);
            }
        });
        add(btn_Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 210, -1, -1));

        btn_Reanudar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/Play2.png"))); // NOI18N
        btn_Reanudar.setActionCommand("Pausa");
        btn_Reanudar.setBorderPainted(false);
        btn_Reanudar.setContentAreaFilled(false);
        btn_Reanudar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_ReanudarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_ReanudarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_ReanudarMousePressed(evt);
            }
        });
        add(btn_Reanudar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, -1, -1));

        jl_ControlMenu.setFont(new java.awt.Font("Hemi Head Rg", 1, 18)); // NOI18N
        jl_ControlMenu.setForeground(new java.awt.Color(255, 255, 255));
        jl_ControlMenu.setText("2");
        add(jl_ControlMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 420, 30, -1));

        jl_ControlReanudar.setFont(new java.awt.Font("Hemi Head Rg", 1, 18)); // NOI18N
        jl_ControlReanudar.setForeground(new java.awt.Color(255, 255, 255));
        jl_ControlReanudar.setText("1");
        add(jl_ControlReanudar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 420, 20, -1));

        jl_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/Semi-Oscuro.png"))); // NOI18N
        add(jl_Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 700));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ReanudarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ReanudarMouseExited
        btn_Reanudar.setIcon(rean2);
    }//GEN-LAST:event_btn_ReanudarMouseExited

    private void btn_ReanudarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ReanudarMouseEntered
        btn_Reanudar.setIcon(rean1);
    }//GEN-LAST:event_btn_ReanudarMouseEntered

    private void btn_ReanudarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ReanudarMousePressed
        btn_Reanudar.setIcon(rean3);
    }//GEN-LAST:event_btn_ReanudarMousePressed

    private void btn_MenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_MenuMouseExited
        btn_Menu.setIcon(home2);
    }//GEN-LAST:event_btn_MenuMouseExited

    private void btn_MenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_MenuMouseEntered
        btn_Menu.setIcon(home1);
    }//GEN-LAST:event_btn_MenuMouseEntered

    private void btn_MenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_MenuMousePressed
        btn_Menu.setIcon(home3);
    }//GEN-LAST:event_btn_MenuMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Menu;
    private javax.swing.JButton btn_Reanudar;
    private javax.swing.JLabel jl_ControlMenu;
    private javax.swing.JLabel jl_ControlReanudar;
    private javax.swing.JLabel jl_Fondo;
    // End of variables declaration//GEN-END:variables
}
